### PR TITLE
Feature/release name

### PR DESCRIPTION
**Pull request by malud**
This PR adds an additional option to pick a release upload target by its name.

See https://github.com/wangyoucao577/assets-uploader/pull/8

### CODE REVIEW

**Comment by wangyoucao577** [comment]
@malud  I have released the assets-uploader, please use this one for the PR: https://github.com/wangyoucao577/assets-uploader/releases/tag/v0.9.0. And I see a lot of changes on the `README.md` and difficult to see the diff. Did you only add one line of `release_name`? Could you please describe a little more on this new arg? Thanks!

**Comment by malud** [comment]
@wangyoucao577 I've reverted the table formatting. Updated the option description.

**Comment by wangyoucao577** [comment]
@malud Thanks for the contribution! Try out the new version please! `wangyoucao577/go-release-action@v1.25`

**Comment by malud** [comment]
Thanks, works 👍🏼

**Pull request merged**
