### PR TITLE
support linux/arm64 platform

### PR DESCRIPTION
**Pull request by kmlebedev**
https://github.com/wangyoucao577/go-release-action/issues/100

### CODE REVIEW

**Comment by wangyoucao577** [comment]
@kmlebedev  So you run this action on your self hosted linux-arm64 runner?  I'm afraid the PR is not enough in this case, at least it should use linux-arm64 go binaries instead https://github.com/wangyoucao577/go-release-action/blob/master/setup-go.sh

Would you please test it with your branch first since I don't have such env(linux-arm64) to verify this change 😆?  Simply try `kmlebedev/go-release-action@issues/100` in your workflow.

**Comment by kmlebedev** [comment]
ok,  I just failed to push the image from an extremely low data transfer rate with the process

```
root@orangepi-rk3399:~# docker push kmlebedev/go-release-action:v1.32
The push refers to repository [docker.io/kmlebedev/go-release-action]
64d1c0bf1e64: Layer already exists
f3bc28315fc7: Pushed
b687eeb696cc: Layer already exists
e7370622f032: Pushing [==>                                                ]  7.697MB/190.4MB
455b047776ff: Layer already exists
```

**Comment by wangyoucao577** [comment]
> ok, I just failed to push the image from an extremely low data transfer rate with the process
> 
> ```
> root@orangepi-rk3399:~# docker push kmlebedev/go-release-action:v1.32
> The push refers to repository [docker.io/kmlebedev/go-release-action]
> 64d1c0bf1e64: Layer already exists
> f3bc28315fc7: Pushed
> b687eeb696cc: Layer already exists
> e7370622f032: Pushing [==>                                                ]  7.697MB/190.4MB
> 455b047776ff: Layer already exists
> ```

@kmlebedev You don't need to push the image. Just use `kmlebedev/go-release-action@{YOUR_BRANCH_NAME}` in your workflow yaml, let github action to build the image on the fly.

**Comment by kmlebedev** [comment]
@wangyoucao577 Done https://github.com/kmlebedev/netbackup-exporter/actions/runs/3454713687
build from this [PR](https://github.com/kmlebedev/go-release-action/releases/tag/v1.33)

**Comment by wangyoucao577** [comment]
> @wangyoucao577 Done https://github.com/kmlebedev/netbackup-exporter/actions/runs/3454713687 build from this [PR](https://github.com/kmlebedev/go-release-action/releases/tag/v1.33)

@kmlebedev  Thanks very much for the excellent feature! Try out `wangyoucao577/go-release-action@v1.33` please!

**Pull request merged**
