### PR TITLE
Spefify Go version by go.mod

### PR DESCRIPTION
**Pull request by hmiyado**
resolve: #99 

This PR enables to specify Go version by go.mod.

### CODE REVIEW

**Comment by wangyoucao577** [comment]
It might be better to use `goversion` var directly, something like `goversion: go.mod` or `goversion: ./project1/go.mod`. If the INPUT_GOVERSION ends with `go.mod`, parse it and use its version.           
By the way, it also needs a test(in https://github.com/wangyoucao577/go-release-action/blob/master/.github/workflows/autotest.yml) to verify new functions.      
Thanks!

**Comment by hmiyado** [comment]
Thank you for your review.

Fixed goversion to specify the path to go.mod directly.

We are currently working on the test as well.
The existing job generates go.mod with the pre_command option.
If go.mod is specified in goversion, go.mod must exist prior to the timing of pre_command.
We believe a separate job is needed.

**Comment by wangyoucao577** [comment]
> Thank you for your review.
> 
> Fixed goversion to specify the path to go.mod directly.
> 
> We are currently working on the test as well. The existing job generates go.mod with the pre_command option. If go.mod is specified in goversion, go.mod must exist prior to the timing of pre_command. We believe a separate job is needed.

Oh, it's ok to create another test app for this test.

**Comment by hmiyado** [comment]
I added new test step in 171948d892128007d0a13317e16e555b438df447.
Please check this when you have time.

**Pull request merged**
