### PR TITLE
feat: add post_command feature to do some teardown work

### PR DESCRIPTION
**Pull request by debugtalk**
1, add post_command feature;  
2, remove extra line suffix spaces by save config;  
3, use `RELEASE_ASSET_FILE` to replace `${RELEASE_ASSET_NAME}${RELEASE_ASSET_EXT}`

### CODE REVIEW

**Comment by wangyoucao577** [comment]
Overall it looks great! Thanks!     
`2, remove extra line suffix spaces by save config;` How did you do that? By some plugin?

**Comment by wangyoucao577** [comment]
> Overall it looks great! Thanks! `2, remove extra line suffix spaces by save config;` How did you do that? By some plugin?

@debugtalk

**Comment by debugtalk** [comment]
@wangyoucao577 configure in my vscode or IDE.

for example, you can set `files.trimTrailingWhitespace` in vscode.

**Comment by debugtalk** [comment]
@wangyoucao577 Can this feature be merged and publish a new version?

**Comment by wangyoucao577** [comment]
> @wangyoucao577 Can this feature be merged and publish a new version?

Here you are: `wangyoucao577/go-release-action@v1.23`

**Comment by debugtalk** [comment]
@wangyoucao577 here is an example to use `post_command`

https://github.com/httprunner/hrp/blob/main/.github/workflows/release.yml

**Pull request merged**
